In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!unzip archive.zip

Archive:  archive.zip
  inflating: crx.data                


In [ ]:
data = pd.read_csv('crx.data')

In [ ]:
data

b  30.83       0  u  g   w   v  1.25  t t.1  01  f g.1  00202  0.1  +
0    a  58.67   4.460  u  g   q   h  3.04  t   t   6  f   g  00043  560  +
1    a  24.50   0.500  u  g   q   h  1.50  t   f   0  f   g  00280  824  +
2    b  27.83   1.540  u  g   w   v  3.75  t   t   5  t   g  00100    3  +
3    b  20.17   5.625  u  g   w   v  1.71  t   f   0  f   s  00120    0  +
4    b  32.08   4.000  u  g   m   v  2.50  t   f   0  t   g  00360    0  +
..  ..    ...     ... .. ..  ..  ..   ... ..  ..  .. ..  ..    ...  ... ..
684  b  21.08  10.085  y  p   e   h  1.25  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.00  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.00  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.04  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.29  f   f   0  t   g  00000    0  -

[689 rows x 16 columns]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

In [ ]:
data[['b','u','g','w','v','t','t.1','f','g.1']] = enc.fit_transform(data[['b','u','g','w','v','t','t.1','f','g.1']])

In [ ]:
data = data.replace('?', np.nan)
data = data.fillna(data.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [ ]:
data.isnull().sum()

b         0
30.83    12
0         0
u         0
g         0
w         0
v         0
1.25      0
t         0
t.1       0
01        0
f         0
g.1       0
00202    13
0.1       0
+         0
dtype: int64

In [ ]:
for cols in data:
  if data[cols].dtypes=='object':
    data = data.fillna(data[cols].value_counts().index[0])

data.isnull().sum()

b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
f        0
g.1      0
00202    0
0.1      0
+        0
dtype: int64

In [ ]:
data.head()

b  30.83      0    u    g     w    v  1.25    t  t.1  01    f  g.1  \
0  1.0  58.67  4.460  2.0  1.0  11.0  4.0  3.04  1.0  1.0   6  0.0  0.0   
1  1.0  24.50  0.500  2.0  1.0  11.0  4.0  1.50  1.0  0.0   0  0.0  0.0   
2  2.0  27.83  1.540  2.0  1.0  13.0  8.0  3.75  1.0  1.0   5  1.0  0.0   
3  2.0  20.17  5.625  2.0  1.0  13.0  8.0  1.71  1.0  0.0   0  0.0  2.0   
4  2.0  32.08  4.000  2.0  1.0  10.0  8.0  2.50  1.0  0.0   0  1.0  0.0   

   00202  0.1  +  
0  00043  560  +  
1  00280  824  +  
2  00100    3  +  
3  00120    0  +  
4  00360    0  +

In [ ]:
data.rename(columns = {'+':'Status'}, inplace = True)

In [ ]:
data['Status'] = data['Status'].map({'+': 1, '-': 0})
data = data.drop(columns=['00202'])
data.head()

b  30.83      0    u    g     w    v  1.25    t  t.1  01    f  g.1  0.1  \
0  1.0  58.67  4.460  2.0  1.0  11.0  4.0  3.04  1.0  1.0   6  0.0  0.0  560   
1  1.0  24.50  0.500  2.0  1.0  11.0  4.0  1.50  1.0  0.0   0  0.0  0.0  824   
2  2.0  27.83  1.540  2.0  1.0  13.0  8.0  3.75  1.0  1.0   5  1.0  0.0    3   
3  2.0  20.17  5.625  2.0  1.0  13.0  8.0  1.71  1.0  0.0   0  0.0  2.0    0   
4  2.0  32.08  4.000  2.0  1.0  10.0  8.0  2.50  1.0  0.0   0  1.0  0.0    0   

   Status  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
train = data.iloc[:,:-1]
test = data.iloc[:, -1:]

In [ ]:
train.columns

Index(['b', '30.83', '0', 'u', 'g', 'w', 'v', '1.25', 't', 't.1', '01', 'f',
       'g.1', '0.1'],
      dtype='object')

In [ ]:
test.columns

Index(['Status'], dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

train_x, test_x , train_y, test_y = train_test_split(train, test, random_state=42, train_size=0.8)

In [ ]:
train_x.head()

b  30.83      0    u    g     w    v   1.25    t  t.1  01    f  g.1  \
278  2.0  16.25  0.835  2.0  1.0  10.0  8.0  0.085  1.0  0.0   0  0.0  2.0   
110  1.0  24.50  1.040  3.0  3.0   6.0  3.0  0.500  1.0  1.0   3  0.0  0.0   
82   1.0  22.67  3.500  2.0  1.0   4.0  8.0  3.000  1.0  0.0   0  1.0  0.0   
51   2.0  37.42  2.040  2.0  1.0  13.0  8.0  0.040  1.0  0.0   0  1.0  0.0   
218  1.0  18.92  9.250  3.0  3.0   2.0  8.0  1.000  1.0  1.0   4  1.0  0.0   

      0.1  
278     0  
110   147  
82      0  
51   5800  
218   500

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

## Logisitic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(verbose=1)
lr.fit(train_x,train_y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(verbose=1)

In [ ]:
pred = lr.predict(test_x)

In [ ]:
lr.score(test_x,test_y)

0.8478260869565217

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(pred,test_y)
cm

array([[60,  6],
       [15, 57]])

In [ ]:
acc = accuracy_score(pred,test_y)
acc

0.8478260869565217

## SVM

In [ ]:
from sklearn.svm import SVC
lr = SVC(verbose=1)
lr.fit(train_x,train_y)

[LibSVM]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(verbose=1)

In [ ]:
pred = lr.predict(test_x)

In [ ]:
lr.score(test_x,test_y)

0.8695652173913043

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(pred,test_y)
cm

array([[62,  5],
       [13, 58]])

In [ ]:
acc = accuracy_score(pred,test_y)
acc

0.8695652173913043

## SGDClassifier


In [ ]:
from sklearn.linear_model import SGDClassifier
est = SGDClassifier(l1_ratio= 0.19999999999999996, learning_rate= 'optimal', loss= 'huber', penalty= 'l2')
est.fit(train_x,train_y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(l1_ratio=0.19999999999999996, loss='huber')

In [ ]:
pred = est.predict(test_x)

In [ ]:
est.score(test_x,test_y)

0.8478260869565217

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(pred,test_y)
cm

array([[57,  3],
       [18, 60]])

In [ ]:
acc = accuracy_score(pred,test_y)
acc

0.8478260869565217

## Grid Search on SGD

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier
est = SGDClassifier()


parameters = {"penalty":['l1','l2'],
              "loss": ['hinge', 'log_loss', 'log', 'modified_huber', 'squared_hinge', 'perceptron', 'squared_error', 'huber', 'epsilon_insensitive', 'squared_epsilon_insensitive'] ,
              "l1_ratio" :np.arange(0.1,0.5,0.01),
              "learning_rate": ['constant','optimal','invscaling','adaptive']
}
grid_search = GridSearchCV(estimator = est,  
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv=10,
                           verbose=0)
grid_search.fit(train_x, train_y)

Streaming output truncated to the last 5000 lines.
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d

GridSearchCV(cv=10, estimator=SGDClassifier(),
             param_grid={'l1_ratio': array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
       0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49]),
                         'learning_rate': ['constant', 'optimal', 'invscaling',
                                           'adaptive'],
                         'loss': ['hinge', 'log_loss', 'log', 'modified_huber',
                                  'squared_hinge', 'perceptron',
                                  'squared_error', 'huber',
                                  'epsilon_insensitive',
                                  'squared_epsilon_insensitive'],
                         'penalty': ['l1', 'l2']},
             scoring='accuracy')

In [ ]:
print(grid_search.best_score_)
print(grid_search.best_params_)
print(grid_search.best_estimator_)

0.8675324675324674
{'l1_ratio': 0.19999999999999996, 'learning_rate': 'optimal', 'loss': 'huber', 'penalty': 'l2'}
SGDClassifier(l1_ratio=0.19999999999999996, loss='huber')


## Grid Search on Logistic Regression


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
est = LogisticRegression()


parameters = {"penalty":['l1','l2','elasticnet','none'],
              "solver": ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'] ,
              "l1_ratio" :np.arange(0.1,0.5,0.01),
            
}
grid_search = GridSearchCV(estimator = est,  
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv=10,
                           verbose=0)
grid_search.fit(train_x, train_y)

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1479: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=none)
  "(penalty={})".format(self.penalty)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1479: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=none)
  "(penalty={})".format(self.penalty)
/usr/

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'l1_ratio': array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
       0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49]),
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [ ]:
print(grid_search.best_score_)
print(grid_search.best_params_)
print(grid_search.best_estimator_)

0.8729545454545453
{'l1_ratio': 0.1, 'penalty': 'none', 'solver': 'newton-cg'}
LogisticRegression(l1_ratio=0.1, penalty='none', solver='newton-cg')


In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(l1_ratio=0.1, penalty='none', solver='newton-cg')
lr.fit(train_x,train_y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:1479: UserWarning: l1_ratio parameter is only used when penalty is 'elasticnet'. Got (penalty=none)
  "(penalty={})".format(self.penalty)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(l1_ratio=0.1, penalty='none', solver='newton-cg')

In [ ]:
pred = lr.predict(test_x)

In [ ]:
lr.score(test_x,test_y)

0.8478260869565217

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(pred,test_y)
cm

array([[60,  6],
       [15, 57]])

In [ ]:
acc = accuracy_score(pred,test_y)
acc

0.8478260869565217